---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit the README.Rmd file -->


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Lab report #1

Follow the instructions posted at https://ds202-at-isu.github.io/labs.html for the lab assignment. The work is meant to be finished during the lab time, but you have time until Monday evening to polish things.

Include your answers in this document (Rmd file). Make sure that it knits properly (into the md file). Upload both the Rmd and the md file to your repository.  

All submissions to the github repo will be automatically uploaded for grading once the due date is passed.
Submit a link to your repository on Canvas (only one submission per team) to signal to the instructors that you are done with your submission.

## Step 12.2

Alli Engels - I was able to do this step easily. Once I was able to copy the link I got it into my Rstudio easily. 

## Step 12.3

Alli Engels - I was only able to get the Read.rmd file to work correctly not the Read.md like the directions used. 

## Step 12.4

Alli Engels - I struggled her to find the correct place to send my commits to and it took a minute to do it the correct way. 

## Step 12.5

Alli Engels - This step worked once I figured out the previous step. 

## Step 12.6

Alli Engels - This step took a few tries to see the inputs but I was able to figure out how to see it in the remote github. 
